############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
- name: News
  url: /news/
  weight: 20
- name: Publications
  url: /papers/
  weight: 30
- name: Team
  url: /members/
  weight: 40
- name: Join us
  url: /joining/
  weight: 50
- name: About
  url: /about/
  weight: 60
- name: Citing
  url: /cite
  weight: 70
