############################
## Author
############################

author:
  name:
  image: christmas/FINK_christmas_logo.png
  normalImage: Fink_PrimaryLogo_WEB.svg
  ztf: ztf.svg
  rubin: logo_rubin.svg
  greeting:
  icon:


###############################
## OpenGraph & Twitter Cards
###############################

title: Fink broker
description: "Fink Broker collaboration website"
image: Fink_PrimaryLogo_WEB.svg

###############################
## Christmas Theme
###############################

enableChristmasTheme: false
